steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  env:
  - 'SAUCE_ENABLED=true'
  - 'SAUCE_USERNAME=${_SAUCE_USERNAME}'
  - 'SAUCE_ACCESS_KEY=${_SAUCE_ACCESS_KEY}'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'dist']
# TODO: replace dd-manager.min.js to dd-manager.js for non-minified version
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "./dist/dd-manager.min.js", "gs://${_DDM_BUCKET_NAME}/sdk/dd-manager.js"]
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "./dist/dd-manager.min.js", "gs://${_DDM_BUCKET_NAME}/sdk/dd-manager.min.js"]
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/sdk/'
    paths: ['dist/dd-manager.js', 'dist/dd-manager.min.js']
