steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  env:
  - 'SAUCE_ENABLED=true'
  - 'SAUCE_USERNAME=${_SAUCE_USERNAME}'
  - 'SAUCE_ACCESS_KEY=${_SAUCE_ACCESS_KEY}'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'dist']
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "./dist/segmentstream.min.js", "gs://${_DDM_BUCKET_NAME}/sdk/dd-manager.js"]
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "./dist/segmentstream.min.js", "gs://${_DDM_BUCKET_NAME}/sdk/dd-manager.min.js"]
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/sdk/'
    paths: ['dist/segmentstream.js', 'dist/segmentstream.min.js']
timeout: 840s
